{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-db
  labels:
    app: {{ .Chart.Name }}
    component: database
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: {{ .Chart.Name }}
    component: database
  clusterIP: None  # Headless service for StatefulSet
{{- end }}
