{{- if .Values.database.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-db-data
  labels:
    app: {{ .Chart.Name }}
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.database.storage.className }}
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
{{- end }}
