{{- if .Values.database.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-db-config
  labels:
    app: {{ .Chart.Name }}
    component: database
data:
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             all                     trust
{{- end }}
